### ISSUE TITLE
Blank window?

### ISSUE THREAD

**Issue by msbit** [ruby2d/ruby2d#110]
May be a matter of compatibility, but running the testcard shows a blank screen with no errors, which stays visible until I close it manually.

This is also the case when running little test programs, eg the listing on http://www.ruby2d.com/

Running under:

Mac OSX 10.7.5
Ruby 2.5.1
Simple2D 0.9.0
SDL2 2.0.8
SDL2-image 2.0.3
SDL2-mixer 2.0.2
SDL2-ttf 2.0.14

Output follows:

```
$ rake test:int testcard

==> Running interpreted test: testcard.rb

==> ( cd test/ && ruby testcard.rb )
=== Window Attributes ===
Title: Ruby 2D — Test Card
Background: #<Ruby2D::Color:0x00007fe3e398da18>
Width:  700
Height: 500
Window: #<Ruby2D::Window:0x00007fe3e398dab8>

Info: Current display mode is 1280x800px @ 60hz
Info: OpenGL Context
      GL_VENDOR: Apple Computer, Inc.
      GL_RENDERER: Apple Software Renderer
      GL_VERSION: 3.2 APPLE
      GL_SHADING_LANGUAGE_VERSION: 1.50
Info: Closing window
Info: Free image: 590, 290
Info: Free image: 590, 400
Info: Free image: 400, 200
Info: Free image: 400, 225
Info: Free image: 425, 225
Info: Free text: R
Info: Free text: G
Info: Free text: B
Info: Free text: FPS: 33.15
Info: Free sprite: 450, 200
Info: Free image: 590, 180
Info: Free text: Created text
Info: Free text: Updated text size
```

**Comment by blacktm** [comment]
Haven't been able to reproduce this, but probably is due to the older OS X version, particularly the less-than OpenGL 3.3 version. Looks like OS X 10.9 (Mavericks) was the [first version to support 3.3+](https://www.cultofmac.com/233030/os-x-mavericks-will-boost-graphics-performance-on-even-older-macs). If interested, you could test on <10.9 and forcing OpenGL 2.1 — there's a flag in Simple 2D to [force it here](https://github.com/simple2d/simple2d/blob/v1.0.1/src/gl.c#L5).
