### ISSUE TITLE
Fullscreen mode not working on macOS 10.14.1

### ISSUE THREAD

**Issue by Makoren** [ruby2d/ruby2d#134]
All I'm doing is using the "set" method in the DSL to change the fullscreen value to true. It attempts to open a window in fullscreen, but it's completely black, even after trying to draw something on it or change the background.

EDIT: Tested on my Windows 10 computer and it works fine.

**Comment by blacktm** [comment]
Yea, this might be due to macOS 10.14 and the breaking change it introduced in SDL: https://discourse.libsdl.org/t/macos-10-14-mojave-issues/25060
It’s fixed in SDL 2.0.9, but now there’s an issue with that version [in Homebrew](https://github.com/Homebrew/homebrew-core/pull/33781). Not sure how to get around all this in an elegant way.

**Comment by blacktm** [comment]
Can confirm this has been fixed in SDL. You should be able to run `brew upgrade` to get SDL 2.0.9 with an updated Simple 2D, then reinstall the Ruby 2D gem.
