### ISSUE TITLE
Implementation of File.exists?

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#21]
Hey

First of all, spectacular work! This is exactly what I needed to revive my pet project: ).

Now to the business: I noticed none of the files that take a path to asset are checking for the existence of that path, and I also noticed that you want them to do so, but the problem is mruby missing `File` class.

I found this: https://github.com/iij/mruby-io to implement the `File` class, and it also seems that MRuby has it's own gems environment, which is setup in that `build_config.rb` file. Those gems seem to have a lot of things that would be useful. Could you please share if you have any plans on integrating with it? Currently those methods throw segfaults. I'm also glad to provide some PRs if you point me to a good direction and they don't involve hacking c code: )

**Comment by blacktm** [comment]
Hi there, glad you like the project!

Yes, the vision for MRuby is to keep the language extremely slim, so as not to burden small computing devices. Makes sense, but sure is a pain when so many classes and methods are missing. Since Ruby 2D isn't intended for those super tiny, embedded platforms (even the $5 Raspberry Pi Zero has some pretty [beefy specs](https://en.wikipedia.org/wiki/Raspberry_Pi#Specifications)), I think it's completely reasonable to include all the standard library gems and try to make it as close to a normal Ruby environment as possible.

I don't really know how mrbgems works yet, but there's a good overview [in the repo](https://github.com/mruby/mruby/blob/master/doc/guides/mrbgems.md). This is probably a good time to start digging in and figure out how to incorporate these gems, and ultimately make them available to a compiled Ruby 2D app.

**Comment by KillaPL** [comment]
My bad, closed bad issue.

**Comment by KillaPL** [comment]
@blacktm Maybe we can do

``` defined?(File) and File.exists?(path)```

?

Such PR can be created in a matter of minutes, and it would work in mri, and possibly in web. Bringing this to native would then be a smaller issue than not having those guards at all. What do you think?

**Comment by blacktm** [comment]
With #52, I think we've met the basic requirements for a `File.exists?`. Not perfect, particularly in Opal, but good enough to close this.
