### ISSUE TITLE
Native file exits without crash

### ISSUE THREAD

**Issue by KillaPL** [ruby2d/ruby2d#22]
Hi

I'm experimenting with ruby2d a little bit and I'm having a problem. This program:

```
require 'ruby2d'

@fps_text = Text.new(15, 15, "fps: 0", 40, "fonts/arial.ttf")

update do
  fps = get(:fps)
  @fps_text.remove
  @fps_text.text = fps.to_s
  @fps_text.add
end

show
```

Is executing properly (provided there is font in proper place) under MRI, is being built properly with `ruby2d build` command, but when I'm tring to open the compiled problem, it opens the window for a split second and closes without any exception.

What behavior should I be expecting here?

**Comment by blacktm** [comment]
Ugh, `remove`, defined in `Ruby2D::Window`, is calling `Array#slice!` on its internal collection of drawable objects, and (surprise) that array method isn't defined in MRuby. Looks like we'd have to use [`Array#delete_at`](https://github.com/mruby/mruby/blob/master/test/t/array.rb#L116) instead. I wonder if there's some debug mode we can enable to discover missing classes/methods, because exiting silently makes for quite a frustrating experience. Either way, good catch!

At least there's good news in your example. You don't actually need to call `remove` or `add` here — these methods are used for removing drawable objects from the window's very rudimentary scene graph (just an array) and adding them back. Since all you're trying to do is update the text, you can delete those two lines entirely (unless this is part of a larger app, in which case might have to wait to use `remove` natively until after it's fixed in the gem).

**Comment by blacktm** [comment]
Since that was the only use of `Array#slice!` in the lib, just made a quick fix in 54b00eb9d3cba566bf80daf6be4c93c1149a7633.

**Comment by KillaPL** [comment]
I actually found out that I don't need to use #remove and #add, however, if I don't do that, the text is not visible if I'm using images for background.

I uploaded my code so you can see the issue for yourself: https://github.com/KillaPL/ruby2d-the-game/blob/disappearing-text/index.rb#L40-L42

Of you `ruby index.rb` this file, you see an fps counter in top left, however if you remove those #remove and #add methods, you can no longer see it. Why does it behave like this? 

Should I create new issue for this, since this is actually a separate issue?
Also, if it's possible to return any sort of exceptions from build native file, this would be much helpful, as I would most likely be able to find the problem myself and provide a pull request.

**Comment by blacktm** [comment]
Regarding the `remove` and `add` behavior, that's expected. Objects are drawn in the order they're created. So as soon as you run `Square.new` for example, the window stores it in its internal `objects` array and iterates through that array to render them. You can see what drawable objects exist in the window using `(get :window).objects`

When you run `remove`, it deletes the object from the array, and `add` will push it to the end of the array, so it's the last thing to get drawn. Rather than removing and adding, make sure you create objects in the order you want them to appear. That said, I do see how it could be helpful to have some methods for bringing object to the front, or pushing back.

**Comment by KillaPL** [comment]
What do you think about adding `z-index` property to rendered objects, that would allow system to sort all necessary files and render as expected? 

This seems like a good idea to say: "I want that object below, that object on the same level, and the other object above all of them, figure out how to do it" instead of rerendering by hand.

**Comment by KillaPL** [comment]
Either way I'm closing this issue, since problem I had was solved. If I get to having issues with z-index, I'll try to suggest an implementation. Thanks!

**Comment by blacktm** [comment]
Sounds good. I'm a bit leery about setting z-indexes generally. For example, I mostly work with the web and only time I see those get set in CSS is as a hack to force correct layout (and cringe when I see stuff like `z-index: 10000;`). Maybe this is more accepted in the game/graphics world. While I think generally creating objects in the order people want them displayed will probably meet most needs, and maybe some helpers to "send to front/back", I get the indention to have more control. Maybe we can discuss layout, scene graph stuff in a new issue.
