### ISSUE TITLE
Stop method for Sound instances

### ISSUE THREAD

**Issue by coontail** [ruby2d/ruby2d#55]
Would it be possible to implement a stop method for Sound instances ?

**Comment by blacktm** [comment]
Hi @Galaad-Gauthier. We originally decided not to give `Sound` a stop method, since the intent for the class was to represent short sounds, like an explosion or something, whereas `Music` would be for longer pieces that you would naturally want to stop, pause, fadeout, etc. It would be a bit of work to add those methods to `Sound`, so I'd be interested to hear your use case, what you're trying to solve for, and if `Music` might meet your needs instead.

**Comment by blacktm** [comment]
Going to close, but happy to reopen if we find a valid use case.

**Comment by Galaad-Gauthier** [comment]
​Well i've been working on a simple point-and-click game prototype.

Today, I can use *Music *instances to play/stop/pause a background music,
and *Sound *instances to play short sound effects.

However, in the case of dialogues, I would like to be able to stop them in
case the player skips them or moves away from the talking character.


It can also allow game devs to avoid having the same sound effect overlap
itself too many times (for instance, if 3 explosions occur in less than 5
seconds, and your sound effect lasts 2 seconds)


2017-05-20 4:27 GMT+02:00 Tom Black <notifications@github.com>:

**Comment by KillaPL** [comment]
Is there anything stopping you from using `Music` class for dialogues?

**Comment by Galaad-Gauthier** [comment]
I'm not sure. Is it possible to have multiple instances of Music playing at
the same time?

2017-05-20 13:09 GMT+02:00 Łukasz Strzebińczyk <notifications@github.com>:

**Comment by blacktm** [comment]
Ah yes, that's a reasonable scenario. `Music` is a global thing, so only one instance can play at a time, so that won't do. We'll reopen and see what it would take to implement.

**Comment by mariovisic** [comment]
The stop method for sounds has been implemented in #260 so will close this off now :)
